### ISSUE TITLE
Regarding the issue of the testing model

### ISSUE THREAD

**Issue by Wolfboyccc** [cjpcool/SAMGC#2]
Evaluating with samgc_acm_for_test.pkl does not yield the results mentioned in the Read file. Could you please explain why?

**Comment by cjpcool** [comment]
Could you please provide more details about your reproduction process? In general, the results might be vary slightly when training on different machines with different environments. However, testing results with *.pkl should be consistent with the reported ones.

**Comment by Wolfboyccc** [comment]
The entire code, I only modified the line model = MultiGraphAutoEncoder(feat_dim, hidden_dim, latent_dim, class_num, lam_emd=lam_emd, order=order, view_num=graph_num), removing the lam_emd parameter because keeping it would result in a TypeError: __init__() got an unexpected keyword argument 'lam_emd'. Then, I proceeded to evaluate using samgc_acm_for_test.pkl, and the obtained results are as follows:
![image](https://github.com/cjpcool/SAMGC/assets/92250129/33f15569-f062-437a-8acd-8ea80ba220cf)

**Comment by cjpcool** [comment]
Hi,

Thanks for your reply and detailed information. 

The issue is arisen due to the version difference. I uploaded the latest version, and hope the new version can address your concern. Please note that use the hyperparameters shown in [test.sh](https://github.com/cjpcool/SAMGC/blob/main/test_acm.sh) for testing. You can test SAMGC via `sh test.sh` or `python samgc.py --dataset 'acm' --model_name 'samgc_acm_for_test.pkl' --order 16 --hidden_dim 256 --latent_dim 64 --use_cuda True --cuda_device 0` to run the model.

Again, we appreciate your issues, and feel free to contact us if you have any further questions in reproducing SAMGC.

Best regards.
